/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Storybook/docs-only metadata describing how the Figma "Icons" section groups
 * icons that have been migrated into `packages/open-ui-kit/src/icons`.
 *
 * This mirrors the exact structure of the Figma file (top-level "General
 * system icons" / "Feature related icons" headers, each containing named
 * category frames such as "Arrows" or "Agentic Services"). It is derived by
 * matching each icon's Figma node-id to the category frame it is nested in
 * (see docs/guides/icon-migration-tracker.md for the per-icon node-ids).
 *
 * Update this file whenever a new icon is migrated into `icons/`, so the
 * grouped Iconography Storybook page stays in sync with Figma's taxonomy.
 * Categories with no migrated icons yet are simply omitted — they'll appear
 * automatically once an icon from that category is added here.
 */

export interface IconCategory {
  /** Category name, matching the Figma category frame name exactly. */
  name: string;
  /** Exported names from `packages/open-ui-kit/src/icons`, in Figma order. */
  iconNames: string[];
}

export interface IconCategoryGroup {
  /** Top-level Figma section header, e.g. "General system icons". */
  group: string;
  categories: IconCategory[];
}

export const ICON_CATEGORY_GROUPS: IconCategoryGroup[] = [
  {
    group: "General system icons",
    categories: [
      {
        name: "Arrows",
        iconNames: [
          "ArrowDown",
          "ArrowUp",
          "ArrowForward",
          "ArrowBack",
          "ArrowOutward",
          "ArrowInsert",
          "CallMade",
          "CallReceived",
          "NorthEast",
          "NorthWest",
          "SouthWest",
          "SouthEast",
          "KeyboardArrowLeft",
          "KeyboardArrowRight",
          "KeyboardArrowUp",
          "KeyboardArrowDown",
          "TriangleDown",
          "TriangleUp",
          "TriangleLeft",
          "TriangleRight",
          "Expand",
          "ExpandContent",
          "Collapse",
          "CollapseContent",
          "OpenFullscreen",
          "CloseFullscreen",
          "Counter",
          "OpenInNew",
          "OpenInNewTab",
          "Replay",
          "KeyboardDoubleArrowDown",
          "KeyboardDoubleArrowUp",
          "KeyboardDoubleArrowRight",
          "KeyboardDoubleArrowLeft",
          "Upload",
          "Download",
          "ArrowBackIos",
          "ArrowForwardIos",
          "ArrowDoubleLeftRight",
          "Swap",
          "Merge",
          "Redo",
          "Undo",
          "ArrowDownCircleFilled",
          "LongArrow",
          "OpenFullPage",
          "Publish",
          "ArrowMenuClose",
          "ArrowMenuOpen",
          "PromptSuggestion",
        ],
      },
      {
        name: "Profile",
        iconNames: [
          "AccountCircle",
          "AccountCircleLive",
          "PersonOutline",
          "Groups",
          "Apartment",
          "Logout",
          "Login",
          "CreditCard",
          "Assign",
          "Payments",
          "Share",
          "AddUser",
          "DarkMode",
          "LightMode",
        ],
      },
      {
        name: "Visibility",
        iconNames: [
          "Visibility",
          "VisibilityOff",
          "Lock",
          "LockOff",
          "PrivateIp",
          "Public",
        ],
      },
      {
        name: "Edit & install",
        iconNames: [
          "Install",
          "Uninstall",
          "Delete",
          "DeleteFilled",
          "Edit",
          "Settings",
          "SettingsFilled",
          "SettingsOutline",
          "BuildOutline",
          "Resize",
        ],
      },
      {
        name: "Close",
        iconNames: [
          "Close",
          "CloseSmall",
          "CloseLarge",
          "CloseCircleOutline",
          "CloseCircleFilled",
          "Block",
        ],
      },
      {
        name: "Messaging",
        iconNames: ["Messaging"],
      },
      {
        name: "Check",
        iconNames: [
          "Check",
          "CheckSmall",
          "CheckCircle",
          "Verified",
          "CheckCircleFill",
          "CheckSquareOutlined",
          "CheckSquareFilled",
        ],
      },
      {
        name: "Alerts",
        iconNames: [
          "Warning",
          "WarningFilled",
          "EmergencyOutlined",
          "EmergencyFilled",
          "ErrorCircleOutline",
          "ErrorCircleFill",
        ],
      },
      {
        name: "Info",
        iconNames: ["InfoCircleOutline", "InfoCircleFilled"],
      },
      {
        name: "Question",
        iconNames: ["Help"],
      },
      {
        name: "Notification",
        iconNames: [
          "NotificationOutlined",
          "NotificationOffOutline",
          "NotificationActiveOutline",
          "NotificationImportantOutlined",
          "Lightbulb",
        ],
      },
      {
        name: "Plus & Minus",
        iconNames: [
          "Minus",
          "MinusCircleOutline",
          "MinusCircleFilled",
          "Plus",
          "PlusCircleOutline",
          "AddCircleFill",
          "Partial",
          "Equal",
          "NotEqual",
        ],
      },
      {
        name: "Time",
        iconNames: [
          "Restore",
          "Update",
          "Realtime",
          "Clock",
          "Calendar",
          "EditCalendar",
          "Reload",
          "Stopwatch",
          "StopwatchOff",
          "Timeline",
          "Synchronize",
        ],
      },
      {
        name: "Image & Media",
        iconNames: [
          "ImageOutline",
          "ImageLibrary",
          "ImageAdd",
          "ImageSearch",
          "ImageValid",
          "PauseCircleOutline",
          "PlayCircleOutline",
          "StopCircleOutline",
          "PauseOutline",
          "Pause",
          "PlayOutline",
          "StopOutline",
          "SkipPrevious",
          "SkipNext",
          "FastRewind",
          "FastForward",
          "Screenshot",
        ],
      },
      {
        name: "Menu, Search, Filter & Sort",
        iconNames: [
          "Menu",
          "MenuList",
          "More",
          "Dots",
          "All",
          "Search",
          "SearchList",
          "DisplayBy",
          "GroupBy",
          "ViewBy",
          "Filter",
          "Sort",
          "FunnelOutline",
          "StarFilled",
          "StarEmpty",
          "StarHalf",
          "GraphView",
          "Category",
        ],
      },
      {
        name: "Content",
        iconNames: [
          "ContentCopy",
          "List",
          "Documentation",
          "ThumbsUp",
          "ThumbsDown",
          "Hand",
          "Link",
          "Unlink",
          "Connection",
          "Send",
          "Json",
          "ManageColumns",
          "DragHorizontal",
          "DragVertical",
          "Fork",
          "Label",
          "Editor",
          "BookmarkEmpty",
          "BookmarkFilled",
          "BookmarkAdded",
          "NewFolder",
          "FileUpload",
          "FolderOpen",
          "Palette",
          "Attachment",
          "Bolt",
          "Github",
          "Animation",
          "PhysicalGesture",
          "Cadence",
          "GestureSelect",
          "Layout",
          "EditSquare",
          "BarChart",
          "KeyboardForwardSlash",
        ],
      },
    ],
  },
  {
    group: "Feature related icons",
    categories: [
      {
        name: "Agentic Services",
        iconNames: ["Agent"],
      },
      {
        name: "Policies",
        iconNames: [
          "SecurityGraph",
          "CloudConfiguration",
          "WorkloadProtection",
          "Discovery",
        ],
      },
      {
        name: "Network",
        iconNames: ["NetworkFilled", "NetworkOutline", "Reachable"],
      },
      {
        name: "API",
        iconNames: ["Api", "ApiSensitive", "ApiAttackPath", "ApiRisky"],
      },
      {
        name: "Bug",
        iconNames: ["Bug", "Zombie", "Shadow", "Rogue"],
      },
      {
        name: "Data",
        iconNames: [
          "Database",
          "DatabaseSensitive",
          "DatabaseRisky",
          "DatabaseAttackPath",
          "DataManualLabeling",
          "DataLake",
          "MemoryStore",
          "ServerlessScan",
          "DataSecurity",
          "Cdr",
        ],
      },
      {
        name: "Asset inventory",
        iconNames: [
          "AssetInventory",
          "GaugeOutline",
          "GaugeFilled",
          "Sensitive",
          "SecurityFindings",
          "Pin",
        ],
      },
      {
        name: "Left Nav",
        iconNames: [
          "RootCauseAnalysis",
          "RuntimeEvents",
          "AttackPath",
          "Reports",
          "VulnerabilityManagement",
          "CodeSecurity",
          "PostureRisks",
          "ExternalAttackSurface",
          "ComplianceReport",
          "ScanReport",
          "SecurityPosture",
        ],
      },
      {
        name: "Health & Safety",
        iconNames: [
          "HealthStatus",
          "HealthStatusHeart",
          "Scan",
          "ShieldKeyOutline",
          "ShieldKeyFilled",
          "ShieldOutlineWarning",
          "ShieldFilledWarning",
          "ShieldApproved",
          "Attack",
          "SuspiciousActivity",
        ],
      },
      {
        name: "Mitre",
        iconNames: [
          "Mitre",
          "MitreExecution",
          "MitrePriviledgeEscalation",
          "MitreDefenceEvasion",
          "MitreCredentialAccess",
          "MitreInitialAccess",
          "MitreDiscovery",
          "MitreLateralMovement",
          "MitrePersistence",
          "MitreCommandControl",
          "MitreImpact",
          "MitreResourcesDevelopment",
          "MitreExfiltration",
        ],
      },
      {
        name: "Security Posture & AP Categories",
        iconNames: [
          "SecretExposure",
          "CredentialsExposure",
          "NeglectedResource",
          "MalwareInfectedWorkload",
          "DataExposure",
          "UnsupportedSoftware",
          "InsecureConfiguration",
          "InsufficientEncryption",
          "InadequateAuthenticationAuthorization",
          "PublicExposure",
          "InsufficientMonitoring",
          "InadequateLoggingBackup",
          "PermissiveAccess",
        ],
      },
      {
        name: "Code & build",
        iconNames: [
          "PullRequest",
          "VersionManagement",
          "FileScan",
          "IacStack",
          "ImageGrid",
          "FileSystem",
          "DeveloperTools",
          "Singleton",
          "Secret",
          "CodeVulnerability",
          "Terraform",
          "GitlabRepoAsset",
          "GithubRepoAsset",
          "AzureRepoAsset",
          "BitbucketRepoAsset",
          "GitlabGroupAsset",
          "GithubGroupAsset",
          "AzureGroupAsset",
          "BitbucketGroupAsset",
        ],
      },
      {
        name: "Integrations",
        iconNames: [
          "Integrations",
          "Kspm",
          "Falcon",
          "Sysflow",
          "Fluentbit",
          "Jira",
          "Gitlab",
          "AzureDevops",
          "Docker",
          "Oracle",
          "Aws",
          "Azure",
          "Kubernetes",
          "Git",
          "Cloudtrail",
        ],
      },
    ],
  },
];
