blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/outshift-open/open-ui-kit/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://main--68cc22452afe30d90e4ca977.chromatic.com
    about: View our Storybook documentation and component examples
  - name: 🆘 Support
    url: https://github.com/outshift-open/open-ui-kit/discussions/categories/q-a
    about: Get help with implementation questions
  - name: 🔒 Security Vulnerabilities
    url: https://github.com/outshift-open/open-ui-kit/security/advisories/new
    about: Report security vulnerabilities privately (preferred method)