/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import type { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightOrangePalette,
  redPalette,
  lightBluePalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
  bluePalette,
  darkNavyPalette,
  electricBluePalette,
  surfaceDarkPalette,
  surfaceLightPalette,
} from "../style/color-palette";
import { iocTealPalette, iocBackdropPalette } from "./ioc-color-palette";

export const iocVars: VarsType = {
  // Brand
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: iocTealPalette[500],
  brandMidnightBlue: iocBackdropPalette[500],
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: iocTealPalette[500],
  agentcyDarkBlue: iocBackdropPalette[900],
  baseTextDark: darkNavyPalette[400],

  // Text
  baseTextStrong: greyPalette[0],
  baseTextDefault: greyPalette[50],
  baseTextMedium: greyPalette[100],
  baseTextWeak: greyPalette[200],
  baseTextInverse: darkNavyPalette[400],
  baseTextDisabled: greyPalette[400],

  // Background
  baseBackgroundStrong: darkNavyPalette[200],
  baseBackgroundMedium: darkNavyPalette[200],
  baseBackgroundWeak: darkNavyPalette[300],
  baseBackgroundHover: darkNavyPalette[400],

  // Border
  baseBorderDefault: surfaceDarkPalette[400],
  baseBorderStrong: surfaceDarkPalette[200],
  baseBorderMedium: surfaceDarkPalette[300],
  baseBorderWeak: surfaceDarkPalette[600],

  // Brand icon
  brandIconPrimaryDefault: lightBluePalette[700],
  brandIconPrimaryWeak: lightBluePalette[300],
  brandIconPrimaryMedium: lightBluePalette[600],
  brandIconPrimaryStrong: nightPalette[300],
  brandIconSecondaryDefault: electricBluePalette[600],
  brandIconSecondaryWeak: electricBluePalette[500],
  brandIconSecondaryMedium: electricBluePalette[600],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand background
  brandBackgroundPrimaryDefault: lightBluePalette[700],
  brandBackgroundPrimaryWeak: greyPalette[800],
  brandBackgroundPrimaryMedium: tealPalette[900],
  brandBackgroundSecondaryDefault: electricBluePalette[600],
  brandLogoPrimary: lightOrangePalette[600],
  brandLogoSecondary: greyPalette[50],
  brandTextPrimary: lightBluePalette[600],
  brandTextSecondary: greyPalette[50],
  brandTextTertiary: lightOrangePalette[500],

  // Control
  controlBackgroundDefault: surfaceDarkPalette[400],
  controlBackgroundDisabled: surfaceDarkPalette[900],
  controlBackgroundWeak: surfaceDarkPalette[600], // toggle-tab container: clearly visible pill
  controlBackgroundMedium: surfaceDarkPalette[500], // selected tab: clearly elevated
  controlBorderDefault: surfaceDarkPalette[200],
  controlBorderStrong: surfaceDarkPalette[50],
  controlBorderMedium: surfaceDarkPalette[100],
  controlBorderWeak: surfaceDarkPalette[400],
  controlBorderHover: lightBluePalette[700],
  controlBorderActive: nightPalette[200],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: greyPalette[900],
  controlIconDefault: greyPalette[50],
  controlIconStrong: greyPalette[0],
  controlIconMedium: greyPalette[100],
  controlIconWeak: greyPalette[200],
  controlIconHover: lightBluePalette[600],
  controlIconActive: lightBluePalette[700],
  controlIconDisabled: greyPalette[400],
  controlFocusRingWeak: iocTealPalette.alpha10,
  controlFocusRingStrong: iocTealPalette.alpha20,

  // Interactive primary (teal)
  interactivePrimaryDefaultDefault: lightBluePalette[700],
  interactivePrimaryDefaultHover: lightBluePalette[600],
  interactivePrimaryDefaultActive: nightPalette[200],
  interactivePrimaryDefaultDisabled: tealPalette[800],
  interactivePrimaryWeakDefault: greyPalette[800],
  interactivePrimaryWeakHover: greyPalette[600],
  interactivePrimaryWeakActive: surfaceDarkPalette[600],
  interactivePrimaryWeakDisabled: darkNavyPalette[200],

  // Interactive secondary (blue)
  interactiveSecondaryDefaultDefault: electricBluePalette[600],
  interactiveSecondaryDefaultHover: electricBluePalette[500],
  interactiveSecondaryDefaultActive: electricBluePalette[700],
  interactiveSecondaryDefaultDisabled: electricBluePalette[900],
  interactiveSecondaryWeakDefault: greyPalette[900],
  interactiveSecondaryWeakHover: greyPalette[800],
  interactiveSecondaryWeakActive: greyPalette[800],
  interactiveSecondaryWeakDisabled: greyPalette[900],

  // Interactive inverse
  interactiveInverseBackgroundDefault: greyPalette[50],
  interactiveInverseBackgroundHover: surfaceLightPalette[50],
  interactiveInverseBackgroundActive: greyPalette[50],
  interactiveInverseBackgroundDisabled: greyPalette[300],
  interactiveInverseTextDefault: darkNavyPalette[400],
  interactiveInverseTextHover: darkNavyPalette[200],
  interactiveInverseTextActive: darkNavyPalette[400],
  interactiveInverseTextDisabled: greyPalette[200],

  // Interactive text in
  interactiveTextInDefault: lightBluePalette[50],
  interactiveTextInHover: lightBluePalette[50],
  interactiveTextInActive: lightBluePalette[50],
  interactiveTextInDisabled: lightBluePalette[500],

  // Interactive tertiary
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[400],
  interactiveTertiaryActive: lightOrangePalette[600],
  interactiveTertiaryDisabled: "rgba(251,175,69,0.40)",

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: "rgba(0,185,141,0.40)",
  successBackgroundHover: greenPalette[400],
  successBackgroundActive: greenPalette[600],
  successBackgroundWeak: "rgba(0,185,141,0.10)",
  successIconActive: greenPalette[600],
  successIconDisabled: "rgba(0,185,141,0.40)",
  successIconHover: greenPalette[400],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[300],
  successTextHover: greenPalette[200],
  successTextDefault: greenPalette[300],
  successTextInDisabled: greenPalette[500],
  successTextInDefault: greenPalette[50],
  successBorderDisabled: "rgba(0,185,141,0.40)",
  successBorderActive: greenPalette[600],
  successBorderHover: greenPalette[400],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0,185,141,0.10)",
  successIconInDisabled: greenPalette[500],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[400],
  negativeBackgroundActive: redPalette[600],
  negativeBackgroundDisabled: "rgba(198,41,83,0.40)",
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198,41,83,0.10)",
  negativeTextDefault: redPalette[300],
  negativeTextHover: redPalette[200],
  negativeTextActive: redPalette[400],
  negativeBorderActive: redPalette[600],
  negativeBorderHover: redPalette[400],
  negativeBorderDisabled: "rgba(198,41,83,0.40)",
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198,41,83,0.10)",
  negativeIconDisabled: "rgba(198,41,83,0.40)",
  negativeIconActive: redPalette[600],
  negativeIconHover: redPalette[400],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: redPalette[50],
  negativeTextInDisabled: redPalette[500],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette[500],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31,210,255,0.10)",
  excellentBackgroundDisabled: "rgba(31,210,255,0.40)",
  excellentBackgroundHover: lightBluePalette[500],
  excellentBackgroundActive: lightBluePalette[700],
  excellentTextDefault: lightBluePalette[200],
  excellentTextHover: lightBluePalette[100],
  excellentTextActive: lightBluePalette[300],
  excellentTextInDefault: lightBluePalette[50],
  excellentTextInDisabled: lightBluePalette[600],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[500],
  excellentBorderActive: lightBluePalette[700],
  excellentBorderDisabled: "rgba(31,210,255,0.40)",
  excellentBorderWeak: "rgba(31,210,255,0.10)",
  excellentIconDefault: lightBluePalette[500],
  excellentIconHover: lightBluePalette[400],
  excellentIconActive: lightBluePalette[600],
  excellentIconDisabled: "rgba(31,210,255,0.40)",
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette[600],

  // Neutral
  neutralBackgroundDefault: nightPalette[200],
  neutralBackgroundWeak: greyPalette[800],
  neutralBackgroundDisabled: tealPalette[800],
  neutralBackgroundHover: lightBluePalette[700],
  neutralBackgroundActive: nightPalette[300],
  neutralTextDefault: lightBluePalette[300],
  neutralTextHover: lightBluePalette[100],
  neutralTextActive: lightBluePalette[500],
  neutralTextInDefault: greyPalette[900],
  neutralTextInDisabled: nightPalette[200],
  neutralBorderDefault: nightPalette[200],
  neutralBorderHover: lightBluePalette[700],
  neutralBorderActive: nightPalette[300],
  neutralBorderDisabled: tealPalette[800],
  neutralBorderWeak: tealPalette[900],
  neutralIconDefault: lightBluePalette[700],
  neutralIconHover: lightBluePalette[600],
  neutralIconActive: nightPalette[200],
  neutralIconDisabled: tealPalette[800],
  neutralIconInDefault: lightBluePalette[50],
  neutralIconInHover: lightBluePalette[100],
  neutralIconInActive: lightBluePalette[300],
  neutralIconInDisabled: nightPalette[200],

  // Info
  infoBackgroundDefault: electricBluePalette[700],
  infoBackgroundWeak: surfaceDarkPalette[800],
  infoBackgroundDisabled: electricBluePalette[900],
  infoBackgroundHover: electricBluePalette[600],
  infoBackgroundActive: electricBluePalette[700],
  infoTextDefault: bluePalette[100],
  infoTextHover: electricBluePalette[100],
  infoTextActive: electricBluePalette[400],
  infoTextInDefault: greyPalette[900],
  infoTextInDisabled: electricBluePalette[700],
  infoBorderDefault: electricBluePalette[700],
  infoBorderHover: electricBluePalette[600],
  infoBorderActive: electricBluePalette[700],
  infoBorderDisabled: electricBluePalette[900],
  infoBorderWeak: surfaceDarkPalette[500],
  infoIconDefault: electricBluePalette[600],
  infoIconHover: electricBluePalette[500],
  infoIconActive: electricBluePalette[700],
  infoIconDisabled: electricBluePalette[900],
  infoIconInDefault: electricBluePalette[50],
  infoIconInHover: electricBluePalette[100],
  infoIconInActive: bluePalette[100],
  infoIconInDisabled: electricBluePalette[700],

  // Inactive
  inactiveBackgroundDefault: greyPalette[600],
  inactiveBackgroundWeak: "rgba(60,69,81,0.10)",
  inactiveBackgroundDisabled: "rgba(60,69,81,0.40)",
  inactiveBackgroundHover: greyPalette[500],
  inactiveBackgroundActive: greyPalette[700],
  inactiveTextDefault: greyPalette[200],
  inactiveTextHover: greyPalette[100],
  inactiveTextActive: greyPalette[300],
  inactiveTextInDefault: greyPalette[50],
  inactiveTextInDisabled: "rgba(60,69,81,0.40)",
  inactiveBorderDefault: greyPalette[600],
  inactiveBorderHover: greyPalette[500],
  inactiveBorderActive: greyPalette[700],
  inactiveBorderDisabled: "rgba(60,69,81,0.40)",
  inactiveBorderWeak: greyPalette[900],
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[300],
  inactiveIconActive: greyPalette[500],
  inactiveIconDisabled: "rgba(60,69,81,0.40)",
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette[600],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251,175,69,0.10)",
  warningBackgroundHover: lightOrangePalette[400],
  warningBackgroundActive: lightOrangePalette[600],
  warningBackgroundDisabled: "rgba(251,175,69,0.40)",
  warningTextDefault: lightOrangePalette[200],
  warningTextHover: lightOrangePalette[100],
  warningTextActive: lightOrangePalette[300],
  warningTextInDefault: orangePalette[50],
  warningTextInDisabled: lightOrangePalette[500],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[400],
  warningBorderActive: lightOrangePalette[600],
  warningBorderDisabled: "rgba(251,175,69,0.40)",
  warningBorderWeak: "rgba(251,175,69,0.10)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[400],
  warningIconActive: lightOrangePalette[600],
  warningIconDisabled: "rgba(251,175,69,0.40)",
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette[500],

  // Severe warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242,100,61,0.10)",
  severeWarningBackgroundHover: orangePalette[400],
  severeWarningBackgroundActive: orangePalette[600],
  severeWarningBackgroundDisabled: "rgba(242,100,61,0.40)",
  severeWarningTextDefault: orangePalette[200],
  severeWarningTextHover: orangePalette[100],
  severeWarningTextActive: orangePalette[300],
  severeWarningTextInDefault: orangePalette[50],
  severeWarningTextInDisabled: orangePalette[500],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[400],
  severeWarningBorderActive: orangePalette[600],
  severeWarningBorderDisabled: "rgba(242,100,61,0.40)",
  severeWarningBorderWeak: "rgba(242,100,61,0.10)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[400],
  severeWarningIconActive: orangePalette[600],
  severeWarningIconDisabled: "rgba(242,100,61,0.40)",
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette[500],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255,230,89,0.10)",
  moderateBackgroundHover: yellowPalette[400],
  moderateBackgroundActive: yellowPalette[600],
  moderateBackgroundDisabled: "rgba(255,230,89,0.40)",
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[700],
  moderateTextInDefault: yellowPalette[50],
  moderateTextInDisabled: yellowPalette[500],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[400],
  moderateBorderActive: yellowPalette[600],
  moderateBorderDisabled: "rgba(255,230,89,0.40)",
  moderateBorderWeak: "rgba(255,230,89,0.10)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[600],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: "rgba(255,230,89,0.40)",
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette[500],

  // Accent colors
  accentADefault: lavenderPalette[400],
  accentAWeak: darkNavyPalette[100],
  accentBDefault: sunsetPalette[300],
  accentBWeak: greyPalette[900],
  accentCDefault: sunsetPalette[100],
  accentCWeak: greyPalette[800],
  accentDDefault: purplePalette[400],
  accentDWeak: surfaceDarkPalette[500],
  accentEDefault: limePalette[400],
  accentEWeak: tealPalette[900],
  accentFDefault: orangePalette[400],
  accentFWeak: greyPalette[900],
  accentGDefault: nightPalette[200],
  accentGWeak: greyPalette[800],
  accentHDefault: lightBluePalette[600],
  accentHWeak: greyPalette[800],
  accentIDefault: pinkPalette[400],
  accentIWeak: darkNavyPalette[300],
  accentJDefault: tealPalette[400],
  accentJWeak: tealPalette[900],
};
